/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/player/player.component';
import * as import2 from '../../../../src/app/shared/player.service';
const styles_PlayerComponent:any[] = ([] as any[]);
export const RenderType_PlayerComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PlayerComponent,
  data: {}
}
);
export function View_PlayerComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{playerRef: 0}),
    (l()(),import0.ɵeld(0,[
      [
        1,
        0
      ]
      ,
      [
        'player',
        1
      ]

    ]
      ,(null as any),0,'audio',[[
        'style',
        'display: none'
      ]
      ],(null as any),[[
        (null as any),
        'ended'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.PlayerComponent = v.component;
      if (('ended' === en)) {
        const pd_0:any = ((<any>co.playerEnded()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any)))
  ]
  ,(null as any),(null as any));
}
function View_PlayerComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-player',([] as any[]),(null as any),(null as any),(null as any),View_PlayerComponent_0,RenderType_PlayerComponent)),
    import0.ɵdid(57344,(null as any),0,import1.PlayerComponent,[import2.PlayerService],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const PlayerComponentNgFactory:import0.ComponentFactory<import1.PlayerComponent> = import0.ɵccf('app-player',import1.PlayerComponent,View_PlayerComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2J1cmtlaG9sbGFuZC9kZXYvYnVya2Vob2xsYW5kL2tlbmRvLWFuZ3VsYXItaXR1bmVzL3NyYy9hcHAvcGxheWVyL3BsYXllci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYnVya2Vob2xsYW5kL2Rldi9idXJrZWhvbGxhbmQva2VuZG8tYW5ndWxhci1pdHVuZXMvc3JjL2FwcC9wbGF5ZXIvcGxheWVyLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2J1cmtlaG9sbGFuZC9kZXYvYnVya2Vob2xsYW5kL2tlbmRvLWFuZ3VsYXItaXR1bmVzL3NyYy9hcHAvcGxheWVyL3BsYXllci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2J1cmtlaG9sbGFuZC9kZXYvYnVya2Vob2xsYW5kL2tlbmRvLWFuZ3VsYXItaXR1bmVzL3NyYy9hcHAvcGxheWVyL3BsYXllci5jb21wb25lbnQudHMuUGxheWVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGF1ZGlvICNwbGF5ZXIgc3R5bGU9XCJkaXNwbGF5OiBub25lXCIgKGVuZGVkKT1cInBsYXllckVuZGVkKClcIj48L2F1ZGlvPiIsIjxhcHAtcGxheWVyPjwvYXBwLXBsYXllcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtNQUFxQztRQUFBO1FBQUE7TUFBQTtNQUFyQztJQUFBOzs7Ozs7SUNBQTtnQkFBQTs7O0lBQUE7OzsifQ==
