/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './artist/artist.component.ngfactory';
import * as import2 from '../../../src/app/shared/itunes.service';
import * as import3 from '@angular/http';
import * as import4 from '../../../src/app/artist/artist.component';
import * as import5 from '../../../src/app/shared/player.service';
import * as import6 from './player/player.component.ngfactory';
import * as import7 from '../../../src/app/player/player.component';
import * as import8 from '../../../src/app/app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AppComponent,
  data: {}
}
);
export function View_AppComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),11,'div',[[
        'class',
        'container'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n	'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['iTunes Search'])),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'app-artist',([] as any[]),(null as any),(null as any),(null as any),import1.View_ArtistComponent_0,import1.RenderType_ArtistComponent)),
    import0.ɵprd(256,(null as any),import2.ItunesService,import2.ItunesService,[import3.Jsonp]),
    import0.ɵdid(24576,(null as any),0,import4.ArtistComponent,[
      import2.ItunesService,
      import5.PlayerService
    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n	'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-player',([] as any[]),(null as any),(null as any),(null as any),import6.View_PlayerComponent_0,import6.RenderType_PlayerComponent)),
    import0.ɵdid(57344,(null as any),0,import7.PlayerComponent,[import5.PlayerService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    ck(v,10,0);
  },(null as any));
}
function View_AppComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'app-root',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
    import0.ɵdid(24576,(null as any),0,import8.AppComponent,([] as any[]),(null as any),(null as any)),
    import0.ɵprd(2304,(null as any),import5.PlayerService,import5.PlayerService,([] as any[]))
  ]
  ,(null as any),(null as any));
}
export const AppComponentNgFactory:import0.ComponentFactory<import8.AppComponent> = import0.ɵccf('app-root',import8.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2J1cmtlaG9sbGFuZC9kZXYvYnVya2Vob2xsYW5kL2tlbmRvLWFuZ3VsYXItaXR1bmVzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9idXJrZWhvbGxhbmQvZGV2L2J1cmtlaG9sbGFuZC9rZW5kby1hbmd1bGFyLWl0dW5lcy9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9idXJrZWhvbGxhbmQvZGV2L2J1cmtlaG9sbGFuZC9rZW5kby1hbmd1bGFyLWl0dW5lcy9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2J1cmtlaG9sbGFuZC9kZXYvYnVya2Vob2xsYW5kL2tlbmRvLWFuZ3VsYXItaXR1bmVzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG5cdDxoMT5pVHVuZXMgU2VhcmNoPC9oMT5cbiAgPGFwcC1hcnRpc3Q+PC9hcHAtYXJ0aXN0PlxuXHQ8YXBwLXBsYXllcj48L2FwcC1wbGF5ZXI+XG48L2Rpdj4iLCI8YXBwLXJvb3Q+PC9hcHAtcm9vdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0FBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBdUI7SUFDdEI7SUFBSTtJQUFrQjtJQUNyQjtnQkFBQTtnQkFBQTs7O0lBQUE7S0FBQTtJQUF5QjtJQUMxQjtnQkFBQTtJQUF5Qjs7O0lBQXpCOzs7OztJQ0hEO2dCQUFBO2dCQUFBOzs7OyJ9
