/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/platform-browser';
import * as import4 from '@angular/forms';
import * as import5 from '@angular/http';
import * as import6 from '@progress/kendo-angular-buttons/dist/es/button/button.module';
import * as import7 from '@progress/kendo-angular-buttons/dist/es/buttongroup/buttongroup.module';
import * as import8 from '@progress/kendo-angular-popup/dist/es/popup.module';
import * as import9 from '@progress/kendo-angular-buttons/dist/es/listbutton/list.module';
import * as import10 from '@progress/kendo-angular-buttons/dist/es/splitbutton/splitbutton.module';
import * as import11 from '@progress/kendo-angular-buttons/dist/es/dropdownbutton/dropdownbutton.module';
import * as import12 from '@progress/kendo-angular-buttons/dist/es/buttons.module';
import * as import13 from '@progress/kendo-angular-dialog/dist/es/dialog.module';
import * as import14 from '@progress/kendo-angular-grid/dist/es/shared.module';
import * as import15 from '@progress/kendo-angular-grid/dist/es/grouping/group.module';
import * as import16 from '@progress/kendo-angular-grid/dist/es/body.module';
import * as import17 from '@progress/kendo-angular-dropdowns/dist/es/shared-directives.module';
import * as import18 from '@progress/kendo-angular-dropdowns/dist/es/shared.module';
import * as import19 from '@progress/kendo-angular-dropdowns/dist/es/dropdownlist.module';
import * as import20 from '@progress/kendo-angular-dropdowns/dist/es/autocomplete.module';
import * as import21 from '@progress/kendo-angular-inputs/dist/es/draggable.module';
import * as import22 from '@progress/kendo-angular-resize-sensor/dist/es/resize-sensor.module';
import * as import23 from '@progress/kendo-angular-inputs/dist/es/slider.module';
import * as import24 from '@progress/kendo-angular-inputs/dist/es/switch.module';
import * as import25 from '@progress/kendo-angular-inputs/dist/es/numerictextbox.module';
import * as import26 from '@progress/kendo-angular-inputs/dist/es/maskedtextbox.module';
import * as import27 from '@progress/kendo-angular-inputs/dist/es/inputs.module';
import * as import28 from '@progress/kendo-angular-grid/dist/es/filtering/filtering.module';
import * as import29 from '@progress/kendo-angular-grid/dist/es/header.module';
import * as import30 from '@progress/kendo-angular-grid/dist/es/footer.module';
import * as import31 from '@progress/kendo-angular-grid/dist/es/pager/pager.module';
import * as import32 from '@progress/kendo-angular-grid/dist/es/grid.module';
import * as import33 from '@progress/kendo-angular-dialog/dist/es/dialog-container.service';
import * as import34 from '@progress/kendo-angular-dialog/dist/es/dialog.service';
import * as import35 from '@progress/kendo-angular-intl/dist/es/cldr-intl.service';
import * as import36 from '../../node_modules/@progress/kendo-angular-dialog/dist/es/dialog.component.ngfactory';
import * as import37 from '../../node_modules/@progress/kendo-angular-dialog/dist/es/dialog-titlebar.component.ngfactory';
import * as import38 from '../../node_modules/@progress/kendo-angular-dialog/dist/es/dialog-actions.component.ngfactory';
import * as import39 from '../../node_modules/@progress/kendo-angular-grid/dist/es/filtering/string-filter-cell.component.ngfactory';
import * as import40 from '../../node_modules/@progress/kendo-angular-grid/dist/es/filtering/numeric-filter-cell.component.ngfactory';
import * as import41 from '../../node_modules/@progress/kendo-angular-grid/dist/es/filtering/boolean-filter-cell.component.ngfactory';
import * as import42 from './app.component.ngfactory';
import * as import43 from '@progress/kendo-angular-intl/dist/es/intl.service';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _APP_INITIALIZER_2:any[];
  _ApplicationInitStatus_3:import0.ApplicationInitStatus;
  _ɵf_4:import0.ɵf;
  _ApplicationRef_5:any;
  _ApplicationModule_6:import0.ApplicationModule;
  _BrowserModule_7:import3.BrowserModule;
  _ɵba_8:import4.ɵba;
  _FormsModule_9:import4.FormsModule;
  _HttpModule_10:import5.HttpModule;
  _JsonpModule_11:import5.JsonpModule;
  _ButtonModule_12:import6.ButtonModule;
  _ButtonGroupModule_13:import7.ButtonGroupModule;
  _PopupModule_14:import8.PopupModule;
  _ListModule_15:import9.ListModule;
  _SplitButtonModule_16:import10.SplitButtonModule;
  _DropDownButtonModule_17:import11.DropDownButtonModule;
  _ButtonsModule_18:import12.ButtonsModule;
  _DialogModule_19:import13.DialogModule;
  _SharedModule_20:import14.SharedModule;
  _GroupModule_21:import15.GroupModule;
  _ReactiveFormsModule_22:import4.ReactiveFormsModule;
  _BodyModule_23:import16.BodyModule;
  _SharedDirectivesModule_24:import17.SharedDirectivesModule;
  _SharedModule_25:import18.SharedModule;
  _DropDownListModule_26:import19.DropDownListModule;
  _AutoCompleteModule_27:import20.AutoCompleteModule;
  _DraggableModule_28:import21.DraggableModule;
  _ResizeSensorModule_29:import22.ResizeSensorModule;
  _SliderModule_30:import23.SliderModule;
  _SwitchModule_31:import24.SwitchModule;
  _NumericTextBoxModule_32:import25.NumericTextBoxModule;
  _MaskedTextBoxModule_33:import26.MaskedTextBoxModule;
  _InputsModule_34:import27.InputsModule;
  _RowFilterModule_35:import28.RowFilterModule;
  _HeaderModule_36:import29.HeaderModule;
  _FooterModule_37:import30.FooterModule;
  _PagerModule_38:import31.PagerModule;
  _GridModule_39:import32.GridModule;
  _AppModule_40:import1.AppModule;
  __LOCALE_ID_41:any;
  __NgLocalization_42:import2.NgLocaleLocalization;
  __Compiler_43:import0.Compiler;
  __APP_ID_44:any;
  __IterableDiffers_45:any;
  __KeyValueDiffers_46:any;
  __DomSanitizer_47:import3.ɵe;
  __Sanitizer_48:any;
  __HAMMER_GESTURE_CONFIG_49:import3.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_50:any[];
  __EventManager_51:import3.EventManager;
  __ɵDomSharedStylesHost_52:import3.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_53:import3.ɵDomRendererFactory2;
  __RendererFactory2_54:any;
  __ɵSharedStylesHost_55:any;
  __Testability_56:import0.Testability;
  __Meta_57:import3.Meta;
  __Title_58:import3.Title;
  __ɵi_59:import4.ɵi;
  __BrowserXhr_60:import5.BrowserXhr;
  __ResponseOptions_61:import5.BaseResponseOptions;
  __XSRFStrategy_62:any;
  __XHRBackend_63:import5.XHRBackend;
  __RequestOptions_64:import5.BaseRequestOptions;
  __Http_65:any;
  __ɵg_66:import5.ɵg;
  __JSONPBackend_67:import5.ɵa;
  __Jsonp_68:any;
  __DialogContainerService_69:import33.DialogContainerService;
  __DialogService_70:import34.DialogService;
  __FormBuilder_71:import4.FormBuilder;
  __IntlService_72:import35.CldrIntlService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import36.DialogComponentNgFactory,
      import37.DialogTitleBarComponentNgFactory,
      import38.DialogActionsComponentNgFactory,
      import39.StringFilterCellComponentNgFactory,
      import40.NumericFilterCellComponentNgFactory,
      import41.BooleanFilterCellComponentNgFactory,
      import42.AppComponentNgFactory
    ]
    ,[import42.AppComponentNgFactory]);
  }
  get _LOCALE_ID_41():any {
    if ((this.__LOCALE_ID_41 == null)) { (this.__LOCALE_ID_41 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_41;
  }
  get _NgLocalization_42():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_42 == null)) { (this.__NgLocalization_42 = new import2.NgLocaleLocalization(this._LOCALE_ID_41)); }
    return this.__NgLocalization_42;
  }
  get _Compiler_43():import0.Compiler {
    if ((this.__Compiler_43 == null)) { (this.__Compiler_43 = new import0.Compiler()); }
    return this.__Compiler_43;
  }
  get _APP_ID_44():any {
    if ((this.__APP_ID_44 == null)) { (this.__APP_ID_44 = import0.ɵg()); }
    return this.__APP_ID_44;
  }
  get _IterableDiffers_45():any {
    if ((this.__IterableDiffers_45 == null)) { (this.__IterableDiffers_45 = import0.ɵl()); }
    return this.__IterableDiffers_45;
  }
  get _KeyValueDiffers_46():any {
    if ((this.__KeyValueDiffers_46 == null)) { (this.__KeyValueDiffers_46 = import0.ɵm()); }
    return this.__KeyValueDiffers_46;
  }
  get _DomSanitizer_47():import3.ɵe {
    if ((this.__DomSanitizer_47 == null)) { (this.__DomSanitizer_47 = new import3.ɵe(this.parent.get(import3.DOCUMENT))); }
    return this.__DomSanitizer_47;
  }
  get _Sanitizer_48():any {
    if ((this.__Sanitizer_48 == null)) { (this.__Sanitizer_48 = this._DomSanitizer_47); }
    return this.__Sanitizer_48;
  }
  get _HAMMER_GESTURE_CONFIG_49():import3.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_49 == null)) { (this.__HAMMER_GESTURE_CONFIG_49 = new import3.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_49;
  }
  get _EVENT_MANAGER_PLUGINS_50():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_50 == null)) { (this.__EVENT_MANAGER_PLUGINS_50 = [
      new import3.ɵDomEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵKeyEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵHammerGesturesPlugin(this.parent.get(import3.DOCUMENT),this._HAMMER_GESTURE_CONFIG_49)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_50;
  }
  get _EventManager_51():import3.EventManager {
    if ((this.__EventManager_51 == null)) { (this.__EventManager_51 = new import3.EventManager(this._EVENT_MANAGER_PLUGINS_50,this.parent.get(import0.NgZone))); }
    return this.__EventManager_51;
  }
  get _ɵDomSharedStylesHost_52():import3.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_52 == null)) { (this.__ɵDomSharedStylesHost_52 = new import3.ɵDomSharedStylesHost(this.parent.get(import3.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_52;
  }
  get _ɵDomRendererFactory2_53():import3.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_53 == null)) { (this.__ɵDomRendererFactory2_53 = new import3.ɵDomRendererFactory2(this._EventManager_51,this._ɵDomSharedStylesHost_52)); }
    return this.__ɵDomRendererFactory2_53;
  }
  get _RendererFactory2_54():any {
    if ((this.__RendererFactory2_54 == null)) { (this.__RendererFactory2_54 = this._ɵDomRendererFactory2_53); }
    return this.__RendererFactory2_54;
  }
  get _ɵSharedStylesHost_55():any {
    if ((this.__ɵSharedStylesHost_55 == null)) { (this.__ɵSharedStylesHost_55 = this._ɵDomSharedStylesHost_52); }
    return this.__ɵSharedStylesHost_55;
  }
  get _Testability_56():import0.Testability {
    if ((this.__Testability_56 == null)) { (this.__Testability_56 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_56;
  }
  get _Meta_57():import3.Meta {
    if ((this.__Meta_57 == null)) { (this.__Meta_57 = new import3.Meta(this.parent.get(import3.DOCUMENT))); }
    return this.__Meta_57;
  }
  get _Title_58():import3.Title {
    if ((this.__Title_58 == null)) { (this.__Title_58 = new import3.Title(this.parent.get(import3.DOCUMENT))); }
    return this.__Title_58;
  }
  get _ɵi_59():import4.ɵi {
    if ((this.__ɵi_59 == null)) { (this.__ɵi_59 = new import4.ɵi()); }
    return this.__ɵi_59;
  }
  get _BrowserXhr_60():import5.BrowserXhr {
    if ((this.__BrowserXhr_60 == null)) { (this.__BrowserXhr_60 = new import5.BrowserXhr()); }
    return this.__BrowserXhr_60;
  }
  get _ResponseOptions_61():import5.BaseResponseOptions {
    if ((this.__ResponseOptions_61 == null)) { (this.__ResponseOptions_61 = new import5.BaseResponseOptions()); }
    return this.__ResponseOptions_61;
  }
  get _XSRFStrategy_62():any {
    if ((this.__XSRFStrategy_62 == null)) { (this.__XSRFStrategy_62 = import5.ɵb()); }
    return this.__XSRFStrategy_62;
  }
  get _XHRBackend_63():import5.XHRBackend {
    if ((this.__XHRBackend_63 == null)) { (this.__XHRBackend_63 = new import5.XHRBackend(this._BrowserXhr_60,this._ResponseOptions_61,this._XSRFStrategy_62)); }
    return this.__XHRBackend_63;
  }
  get _RequestOptions_64():import5.BaseRequestOptions {
    if ((this.__RequestOptions_64 == null)) { (this.__RequestOptions_64 = new import5.BaseRequestOptions()); }
    return this.__RequestOptions_64;
  }
  get _Http_65():any {
    if ((this.__Http_65 == null)) { (this.__Http_65 = import5.ɵc(this._XHRBackend_63,this._RequestOptions_64)); }
    return this.__Http_65;
  }
  get _ɵg_66():import5.ɵg {
    if ((this.__ɵg_66 == null)) { (this.__ɵg_66 = new import5.ɵg()); }
    return this.__ɵg_66;
  }
  get _JSONPBackend_67():import5.ɵa {
    if ((this.__JSONPBackend_67 == null)) { (this.__JSONPBackend_67 = new import5.ɵa(this._ɵg_66,this._ResponseOptions_61)); }
    return this.__JSONPBackend_67;
  }
  get _Jsonp_68():any {
    if ((this.__Jsonp_68 == null)) { (this.__Jsonp_68 = import5.ɵd(this._JSONPBackend_67,this._RequestOptions_64)); }
    return this.__Jsonp_68;
  }
  get _DialogContainerService_69():import33.DialogContainerService {
    if ((this.__DialogContainerService_69 == null)) { (this.__DialogContainerService_69 = new import33.DialogContainerService()); }
    return this.__DialogContainerService_69;
  }
  get _DialogService_70():import34.DialogService {
    if ((this.__DialogService_70 == null)) { (this.__DialogService_70 = new import34.DialogService(this.componentFactoryResolver,this._DialogContainerService_69)); }
    return this.__DialogService_70;
  }
  get _FormBuilder_71():import4.FormBuilder {
    if ((this.__FormBuilder_71 == null)) { (this.__FormBuilder_71 = new import4.FormBuilder()); }
    return this.__FormBuilder_71;
  }
  get _IntlService_72():import35.CldrIntlService {
    if ((this.__IntlService_72 == null)) { (this.__IntlService_72 = new import35.CldrIntlService(this._LOCALE_ID_41)); }
    return this.__IntlService_72;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import3.ɵa();
    this._APP_INITIALIZER_2 = [
      import0.ɵo,
      import3.ɵc(this.parent.get(import3.NgProbeToken,(null as any)),this.parent.get(import0.NgProbeToken,(null as any)))
    ]
    ;
    this._ApplicationInitStatus_3 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_2);
    this._ɵf_4 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_3);
    this._ApplicationRef_5 = this._ɵf_4;
    this._ApplicationModule_6 = new import0.ApplicationModule(this._ApplicationRef_5);
    this._BrowserModule_7 = new import3.BrowserModule(this.parent.get(import3.BrowserModule,(null as any)));
    this._ɵba_8 = new import4.ɵba();
    this._FormsModule_9 = new import4.FormsModule();
    this._HttpModule_10 = new import5.HttpModule();
    this._JsonpModule_11 = new import5.JsonpModule();
    this._ButtonModule_12 = new import6.ButtonModule();
    this._ButtonGroupModule_13 = new import7.ButtonGroupModule();
    this._PopupModule_14 = new import8.PopupModule();
    this._ListModule_15 = new import9.ListModule();
    this._SplitButtonModule_16 = new import10.SplitButtonModule();
    this._DropDownButtonModule_17 = new import11.DropDownButtonModule();
    this._ButtonsModule_18 = new import12.ButtonsModule();
    this._DialogModule_19 = new import13.DialogModule();
    this._SharedModule_20 = new import14.SharedModule();
    this._GroupModule_21 = new import15.GroupModule();
    this._ReactiveFormsModule_22 = new import4.ReactiveFormsModule();
    this._BodyModule_23 = new import16.BodyModule();
    this._SharedDirectivesModule_24 = new import17.SharedDirectivesModule();
    this._SharedModule_25 = new import18.SharedModule();
    this._DropDownListModule_26 = new import19.DropDownListModule();
    this._AutoCompleteModule_27 = new import20.AutoCompleteModule();
    this._DraggableModule_28 = new import21.DraggableModule();
    this._ResizeSensorModule_29 = new import22.ResizeSensorModule();
    this._SliderModule_30 = new import23.SliderModule();
    this._SwitchModule_31 = new import24.SwitchModule();
    this._NumericTextBoxModule_32 = new import25.NumericTextBoxModule();
    this._MaskedTextBoxModule_33 = new import26.MaskedTextBoxModule();
    this._InputsModule_34 = new import27.InputsModule();
    this._RowFilterModule_35 = new import28.RowFilterModule();
    this._HeaderModule_36 = new import29.HeaderModule();
    this._FooterModule_37 = new import30.FooterModule();
    this._PagerModule_38 = new import31.PagerModule();
    this._GridModule_39 = new import32.GridModule();
    this._AppModule_40 = new import1.AppModule();
    return this._AppModule_40;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_2; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_3; }
    if ((token === import0.ɵf)) { return this._ɵf_4; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_5; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_6; }
    if ((token === import3.BrowserModule)) { return this._BrowserModule_7; }
    if ((token === import4.ɵba)) { return this._ɵba_8; }
    if ((token === import4.FormsModule)) { return this._FormsModule_9; }
    if ((token === import5.HttpModule)) { return this._HttpModule_10; }
    if ((token === import5.JsonpModule)) { return this._JsonpModule_11; }
    if ((token === import6.ButtonModule)) { return this._ButtonModule_12; }
    if ((token === import7.ButtonGroupModule)) { return this._ButtonGroupModule_13; }
    if ((token === import8.PopupModule)) { return this._PopupModule_14; }
    if ((token === import9.ListModule)) { return this._ListModule_15; }
    if ((token === import10.SplitButtonModule)) { return this._SplitButtonModule_16; }
    if ((token === import11.DropDownButtonModule)) { return this._DropDownButtonModule_17; }
    if ((token === import12.ButtonsModule)) { return this._ButtonsModule_18; }
    if ((token === import13.DialogModule)) { return this._DialogModule_19; }
    if ((token === import14.SharedModule)) { return this._SharedModule_20; }
    if ((token === import15.GroupModule)) { return this._GroupModule_21; }
    if ((token === import4.ReactiveFormsModule)) { return this._ReactiveFormsModule_22; }
    if ((token === import16.BodyModule)) { return this._BodyModule_23; }
    if ((token === import17.SharedDirectivesModule)) { return this._SharedDirectivesModule_24; }
    if ((token === import18.SharedModule)) { return this._SharedModule_25; }
    if ((token === import19.DropDownListModule)) { return this._DropDownListModule_26; }
    if ((token === import20.AutoCompleteModule)) { return this._AutoCompleteModule_27; }
    if ((token === import21.DraggableModule)) { return this._DraggableModule_28; }
    if ((token === import22.ResizeSensorModule)) { return this._ResizeSensorModule_29; }
    if ((token === import23.SliderModule)) { return this._SliderModule_30; }
    if ((token === import24.SwitchModule)) { return this._SwitchModule_31; }
    if ((token === import25.NumericTextBoxModule)) { return this._NumericTextBoxModule_32; }
    if ((token === import26.MaskedTextBoxModule)) { return this._MaskedTextBoxModule_33; }
    if ((token === import27.InputsModule)) { return this._InputsModule_34; }
    if ((token === import28.RowFilterModule)) { return this._RowFilterModule_35; }
    if ((token === import29.HeaderModule)) { return this._HeaderModule_36; }
    if ((token === import30.FooterModule)) { return this._FooterModule_37; }
    if ((token === import31.PagerModule)) { return this._PagerModule_38; }
    if ((token === import32.GridModule)) { return this._GridModule_39; }
    if ((token === import1.AppModule)) { return this._AppModule_40; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_41; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_42; }
    if ((token === import0.Compiler)) { return this._Compiler_43; }
    if ((token === import0.APP_ID)) { return this._APP_ID_44; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_45; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_46; }
    if ((token === import3.DomSanitizer)) { return this._DomSanitizer_47; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_48; }
    if ((token === import3.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_49; }
    if ((token === import3.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_50; }
    if ((token === import3.EventManager)) { return this._EventManager_51; }
    if ((token === import3.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_52; }
    if ((token === import3.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_53; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_54; }
    if ((token === import3.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_55; }
    if ((token === import0.Testability)) { return this._Testability_56; }
    if ((token === import3.Meta)) { return this._Meta_57; }
    if ((token === import3.Title)) { return this._Title_58; }
    if ((token === import4.ɵi)) { return this._ɵi_59; }
    if ((token === import5.BrowserXhr)) { return this._BrowserXhr_60; }
    if ((token === import5.ResponseOptions)) { return this._ResponseOptions_61; }
    if ((token === import5.XSRFStrategy)) { return this._XSRFStrategy_62; }
    if ((token === import5.XHRBackend)) { return this._XHRBackend_63; }
    if ((token === import5.RequestOptions)) { return this._RequestOptions_64; }
    if ((token === import5.Http)) { return this._Http_65; }
    if ((token === import5.ɵg)) { return this._ɵg_66; }
    if ((token === import5.JSONPBackend)) { return this._JSONPBackend_67; }
    if ((token === import5.Jsonp)) { return this._Jsonp_68; }
    if ((token === import33.DialogContainerService)) { return this._DialogContainerService_69; }
    if ((token === import34.DialogService)) { return this._DialogService_70; }
    if ((token === import4.FormBuilder)) { return this._FormBuilder_71; }
    if ((token === import43.IntlService)) { return this._IntlService_72; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_4.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_52 && this._ɵDomSharedStylesHost_52.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2J1cmtlaG9sbGFuZC9kZXYvYnVya2Vob2xsYW5kL2tlbmRvLWFuZ3VsYXItaXR1bmVzL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9idXJrZWhvbGxhbmQvZGV2L2J1cmtlaG9sbGFuZC9rZW5kby1hbmd1bGFyLWl0dW5lcy9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
