/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './track-control.component.scss.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/common';
import * as import3 from '../../../../../src/app/track/track-control/track-control.component';
import * as import4 from '../../../../../src/app/shared/player.service';
const styles_TrackControlComponent:any[] = [import0.styles];
export const RenderType_TrackControlComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_TrackControlComponent,
  data: {}
}
);
function View_TrackControlComponent_1(l:any):import1.ɵViewDefinition {
    return import1.ɵvid(0,[(l()(),import1.ɵeld(0,(null as any),(null as any),0,'span',[
      [
        'aria-hidden',
        'true'
      ]
      ,
      [
        'class',
        'glyphicon glyphicon-play'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:any = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.playTrack()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
  },(null as any),(null as any)))],(null as any),(null as any));
}
function View_TrackControlComponent_2(l:any):import1.ɵViewDefinition {
    return import1.ɵvid(0,[(l()(),import1.ɵeld(0,(null as any),(null as any),0,'span',[
      [
        'aria-hidden',
        'true'
      ]
      ,
      [
        'class',
        'glyphicon glyphicon-pause'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:any = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.pauseTrack()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
  },(null as any),(null as any)))],(null as any),(null as any));
}
export function View_TrackControlComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),7,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_TrackControlComponent_1)),
    import1.ɵdid(8192,(null as any),0,import2.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n  '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_TrackControlComponent_2)),
    import1.ɵdid(8192,(null as any),0,import2.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import3.TrackControlComponent = v.component;
    const currVal_0:boolean = !co.isPlaying;
    ck(v,3,0,currVal_0);
    const currVal_1:any = co.isPlaying;
    ck(v,6,0,currVal_1);
  },(null as any));
}
function View_TrackControlComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-track-control',([] as any[]),(null as any),(null as any),(null as any),View_TrackControlComponent_0,RenderType_TrackControlComponent)),
    import1.ɵdid(122880,(null as any),0,import3.TrackControlComponent,[import4.PlayerService],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const TrackControlComponentNgFactory:import1.ComponentFactory<import3.TrackControlComponent> = import1.ɵccf('app-track-control',import3.TrackControlComponent,View_TrackControlComponent_Host_0,{track: 'track'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2J1cmtlaG9sbGFuZC9kZXYvYnVya2Vob2xsYW5kL2tlbmRvLWFuZ3VsYXItaXR1bmVzL3NyYy9hcHAvdHJhY2svdHJhY2stY29udHJvbC90cmFjay1jb250cm9sLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9idXJrZWhvbGxhbmQvZGV2L2J1cmtlaG9sbGFuZC9rZW5kby1hbmd1bGFyLWl0dW5lcy9zcmMvYXBwL3RyYWNrL3RyYWNrLWNvbnRyb2wvdHJhY2stY29udHJvbC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9idXJrZWhvbGxhbmQvZGV2L2J1cmtlaG9sbGFuZC9rZW5kby1hbmd1bGFyLWl0dW5lcy9zcmMvYXBwL3RyYWNrL3RyYWNrLWNvbnRyb2wvdHJhY2stY29udHJvbC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2J1cmtlaG9sbGFuZC9kZXYvYnVya2Vob2xsYW5kL2tlbmRvLWFuZ3VsYXItaXR1bmVzL3NyYy9hcHAvdHJhY2svdHJhY2stY29udHJvbC90cmFjay1jb250cm9sLmNvbXBvbmVudC50cy5UcmFja0NvbnRyb2xDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2PlxuICA8c3BhbiAqbmdJZj1cIiFpc1BsYXlpbmdcIiBjbGFzcz1cImdseXBoaWNvbiBnbHlwaGljb24tcGxheVwiIGFyaWEtaGlkZGVuPVwidHJ1ZVwiIChjbGljayk9XCJwbGF5VHJhY2soKVwiPjwvc3Bhbj5cbiAgPHNwYW4gKm5nSWY9XCJpc1BsYXlpbmdcIiBjbGFzcz1cImdseXBoaWNvbiBnbHlwaGljb24tcGF1c2VcIiBhcmlhLWhpZGRlbj1cInRydWVcIiAoY2xpY2spPVwicGF1c2VUcmFjaygpXCI+PC9zcGFuPlxuPC9kaXY+XG4iLCI8YXBwLXRyYWNrLWNvbnRyb2w+PC9hcHAtdHJhY2stY29udHJvbD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MkJDQ0U7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQTZFO1FBQUE7UUFBQTtNQUFBO01BQTdFO0VBQUE7OzsyQkFDQTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO01BQUE7TUFBNkU7UUFBQTtRQUFBO01BQUE7TUFBN0U7RUFBQTs7OztJQUZGO0lBQUs7SUFDSDtnQkFBQTs7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQTBHO0lBQzFHO2dCQUFBOzs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBMkc7SUFDdkc7Ozs7SUFGRTtJQUFOLFNBQU0sU0FBTjtJQUNNO0lBQU4sU0FBTSxTQUFOOzs7OztJQ0ZGO2dCQUFBOzs7SUFBQTs7OyJ9
