/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['span[_ngcontent-%COMP%] {\n    cursor: pointer;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2J1cmtlaG9sbGFuZC9kZXYvYnVya2Vob2xsYW5kL2tlbmRvLWFuZ3VsYXItaXR1bmVzL3NyYy9hcHAvdHJhY2svdHJhY2stY29udHJvbC90cmFjay1jb250cm9sLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2J1cmtlaG9sbGFuZC9kZXYvYnVya2Vob2xsYW5kL2tlbmRvLWFuZ3VsYXItaXR1bmVzL3NyYy9hcHAvdHJhY2svdHJhY2stY29udHJvbC90cmFjay1jb250cm9sLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
